language: perl
os: linux
sudo: false
perl:
  - "5.26"
  - "5.24"
  - "5.20"
env:
  global:
    # some dependencies might require this :(
    - PERL_USE_UNSAFE_INC=1
install:
  # install all dependencies
  - cpanm --quiet --installdeps --notest --with-develop .
script:
  # build and test this dist
  - dzil test --all
  # test installation
  - dzil install
  # ok great thanks :)
